SELECT
    P.PRODUCT_ID,
    CONCAT(
        MAX(P.PROPERTY_NAME),
        '=',
        P.PROPERTY_VALUE
    ) AS PROPERTY_VALUE
FROM QUALISCORE_LAB.LAB_STAGE_HIGH_OFFER_SCORE_PROPERTIES AS P
GROUP BY
    P.PROPERTY_ID,
    P.PROPERTY_VALUE,
    P.PRODUCT_ID;